version: '3.8'
services:
  registry:
    image: registry:2
    ports: ["5000:5000"]

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports: ["8080:8080", "50000:50000"]
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:community
    environment:
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports: ["9000:9000"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana-oss
    ports: ["3000:3000"]

volumes:
  jenkins_home:
